services:
  muehle:
    build: .
    image: muehle:minimal
    container_name: muehle
    restart: unless-stopped
    ports:
      - "5001:5002"
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
